version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      react:
        patterns:
          - "react*"
      tailwindcss:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
          - "tw-animate-css"
      radix-ui:
        patterns:
          - "@radix-ui/*"
      types:
        patterns:
          - "@types/*"
      biome:
        patterns:
          - "@biomejs/*"
      next:
        patterns:
          - "next"
          - "@next/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
