name: Bug report
description: Create a bug report to help me improve the project
title: '[Bug]: <title>'
labels: ["bug"]
assignees:
  - Slartibartfass2
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: what-happend
    attributes:
      label: What happend?
      description: A clear and concise description of what the bug is.
      placeholder: e.g. "When button a is clicked the app crashes."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect?
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. "When button a is clicked the app shouldn't crash."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: On which device did the bug appear
      description: Provide information about the device, OS, browser and the app version.
      value: |
        - Device:
        - OS:
        - Browser:
        - App version:
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give me more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
