blank_issues_enabled: false
contact_links:
  - name: ingredient_collector community support
    url: https://github.com/Slartibartfass2/ingredient_collector/discussions
    about: Please ask and answer questions here.
