name: General issue
description: For anything that doesn't fit the other templates
title: "[General]: "
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the issue or topic ...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Any other details ...
