name: Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup/

      - name: Build application
        run: npm run build
