name: Code Quality Checks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

env:
  node_version: ${{ vars.NODE_VERSION }}

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup
        uses: ./.github/workflows/setup/
        with:
          node_version: ${{ env.node_version }}

      - name: Linting
        run: pnpm run lint

  check:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup
        uses: ./.github/workflows/setup/
        with:
          node_version: ${{ env.node_version }}

      - name: Run all checks
        run: pnpm run check
