name: Code Quality Checks

on: [push]

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Verify JSON validation
        run: npm run validate-json

  spell-checking:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r pages_spellchecker/requirements.txt

      - name: Run spell checking
        run: python3 pages_spellchecker/pages_spellchecker.py

  check-lock-file:
    name: Check lock file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check lock file
        run: git diff --exit-code
